export enum actionTypes {
  SAVE_PRODUCT = "SAVE_PRODUCT",
  UNSAVE_PRODUCT = "UNSAVE_PRODUCT",
  ADD_PRODUCT_TO_RECENT = "ADD_PRODUCT_TO_RECENT",
  REMOVE_PRODUCT_FROM_RECENT = "REMOVE_PRODUCT_FROM_RECENT",
  CLEAR_RECENTLY_VIED = "CLEAR_RECENTLY_VIEWED",
}
