export const SAVE_PRODUCT: string = "SAVE_PRODUCT";
export const UNSAVE_PRODUCT: string = "UNSAVE_PRODUCT";
export const ADD_PRODUCT_TO_RECENT = "ADD_PRODUCT_TO_RECENT";
export const REMOVE_PRODUCT_FROM_RECENT = "REMOVE_PRODUCT_FROM_RECENT";
