export enum actionTypes {
  SAVE_PRODUCT = "SAVE_PRODUCT",
  UNSAVE_PRODUCT = "UNSAVE_PRODUCT",
  ADD_PRODUCT_TO_RECENT = "ADD_PRODUCT_TO_RECENT",
  REMOVE_PRODUCT_FROM_RECENT = "REMOVE_PRODUCT_FROM_RECENT",
  CLEAR_RECENTLY_VIED = "CLEAR_RECENTLY_VIEWED",
  ADD_TO_BAG = "ADD_TO_BAG",
  REMOVE_FROM_BAG = "REMOVE_FROM_BAG",
  UPDATE_SAVED_PRODUCT_SIZE = "UPDATE_SAVED_PRODUCT_SIZE",
}
